name: sober_clock
description: A sober digital clock made in Dart with Flutter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

fonts:
  - family: Dongle
    fonts:
      - asset: fonts\Dongle-Bold.ttf
      - asset: fonts\Dongle-Light.ttf
      - asset: fonts\Dongle-Regular.ttf